### ISSUE TITLE
สอบถามเพิ่มเติม

### ISSUE THREAD

**Issue by kimkimhun** [kimkimhun/testwork-react#1]
อยากสอบถามเกี่ยวกับ search api ครับ เนื่งจากผมได้ลอง ทำการเชื่อมต่อ กับ  client ID and secret ซึ่งพบว่า สามารถส่ง request ได้ 30 ครั้งต่อนาที อยากทราบว่า จะมีผลต่อการให้คะแนนไหมครับ ช่วยให้คำแนะนำในการ เรียกใช้ search api ด้วยครับผม ขอบคุณครับ

**Comment by Elecweb** [comment]
@kimkimhun น้องส่งทุกครั้งที่พิมพ์หรือเปล่าครับ ถ้าใช่พี่แนะนำให้ใช้ rxjs debounceTime มันจะหน่วงเวลาการส่งทำให้ไม่ส่ง request ทุกครั้งที่พิมพ์ครับ
ส่วนเรื่องส่ง request เกินแล้วไม่ได้ ไม่มีผลต่อคะแนนครับ พี่อยากดูโค้ดน้องเป็นหลักครับ

**Comment by kimkimhun** [comment]
ครับผม ขอบคุณครับ

**Comment by Elecweb** [comment]
👍
